version: "3.7"
services:
    # 启动: docker-compose --compatibility up -d
    hfpy_data_server:
        image: haifengat/hfpy_data_server:slim
        container_name: server_slim
        restart: always
        # ports:
        #     - 15555:5055
        environment:
            - TZ=Asia/Shanghai
            # 数据服务端口
            - port=5055
            # redis 实时行情
            - redis_addr=redis_real:6379
            # postgres 历史K线数据
            - pg_config=postgresql://postgres:123456@pg_min:5432/postgres
            # 分钟数据路径
            - min_csv_gz_path=/home/min_csv_gz
        volumes: 
            - /mnt/future_min_csv_gz:/home/min_csv_gz
        depends_on:
            - pg_min
            - redis_real
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 2G
                reservations:
                    memory: 200M

    # 遇到the database system is starting up错误, 配置数据文件下的postgres.conf,hot_standby=on
    pg_min:
        image: postgres:12-alpine
        container_name: pg_min_slim
        restart: always
        environment:
            TZ: "Asia/Shanghai"
            POSTGRES_PASSWORD: "123456"
        # ports:
        #     - "25432:5432"
        volumes:
            - /mnt/pg_min_data:/var/lib/postgresql/data

    real_md:
        image: haifengat/ctp_real_md:slim
        container_name: real_md_slim
        restart: always
        environment:
            - "TZ=Asia/Shanghai"
            - "redis_addr=redis_real:6379"
            - "front_trade=tcp://180.168.146.187:10101"
            - "front_quote=tcp://180.168.146.187:10111"
            - "login_info=008105/1/9999/simnow_client_test/0000000000000000"
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 2G
                reservations:
                    memory: 200M
        depends_on:
            - redis_real

    redis_real:
        image: redis:6.0.8-alpine3.12
        container_name: redis_real_slim
        restart: always
        # ports:
        #     - 16379:6379
        environment:
            - TZ=Asia/Shanghai
      
